name: KapClanPlugin
main: fr.kap35.clans.KapClan
version: 1.0.0
author: kap35
website: https://github.com/benji-35
description: Plugin made to create and manage clans
api-version: 1.19

depend:
  - KapEasyMenu

commands:
  clan:
    description: Open main menu clan
    usage: /clan
    permission: kapclan.menu
    permission-message: You don't have the permission to use this command
